import { makeStyles } from "@mui/styles";

const useStyles = makeStyles((theme) => ({
  noData: {
    width: "440px",
    height: "100%",
    position: "relative",
    "& img": {
      maxWidth: "100%",
    },
    "& p": {
      position: "absolute",
      top: "230px",
      fontSize: `${theme.globals.fontSize.s + 2}px!important`,
      left: "-21px",
      color: "#455a64",
      fontWeight: "700",
    },
  },
  CustomTabs: {
    left: "50%",
    WebkitTransform: "translateX(-50%)",
    transform: "translateX(-50%)",
    position: "relative",
    padding: "0px 5px",
    width: "100%",
    borderRadius: "5px",
    minWidth: "240px",
    marginTop: theme.spacing(3),
    "& > ul": {
      width: "99%",
      overflowX: "auto",
      overflowY: "hidden",
      minHeight: "45px",
      paddingTop: "10px!important",
      height: "41px",
      display: "flex",
      flexWrap: "nowrap",
      alignItems: "center",
      borderBottom: "1px solid #bf9e66",
      paddingLeft: "0",
      flexDirection: "row",
      listStyleType: "none",
      WebkitBoxPack: "justify",
      WebkitBoxAlign: "end",
      WebkitBoxOrient: "horizontal",
      WebkitBoxDirection: "normal",

      [theme.breakpoints.down("624")]: {
        flexWrap: "nowrap",
        overflowX: "scroll",
        height: "49px",
        overflowY: "hidden",
      },
      "& li": {
        margin: "-1px 3px",
        display: "flex",
        padding: "9px 0px",
        fontSize: `${theme.globals.fontSize.xs + 2}px!important`,
        minWidth: "14%",
        background: "#F8F8F8",
        minHeight: "28px",
        whiteSpace: "nowrap",
        borderBottom: "none!important",
        borderRadius: "4px 4px 0 0px",
        justifyContent: "center",
        [theme.breakpoints.down("xs")]: {
          minWidth: "33%",
        },
        "& label": {
          fontSize: theme.globals.fontSize.xs + 2,
          color: "#444",
          padding: "5px auto",
          overflow: "hidden",
          textOverflow: "ellipsis",
          display: "block",
          cursor: "pointer",
          WebkitTransition: "all 0.2s ease-in-out",
          transition: "all 0.2s ease-in-out",
          whiteSpace: "nowrap",
          WebkitTouchCallout: "none",
          userSelect: "none",
          paddingInlineEnd: "19px",
          [theme.breakpoints.down("xs")]: {
            fontSize: theme.globals.fontSize.xs + 1,
          },
          "&:hover": {
            outline: "0",
            color: "#bec5cf",
          },
          "&:active": {
            outline: "0",
            color: "#bec5cf",
          },
          "&:focus": {
            outline: "0",
            color: "#bec5cf",
          },
        },
      },
    },
  },
}));
export default useStyles;
